apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: theapp-depl
  labels:
    app: theapp
    zone: dev
spec:
  replicas: 10
  selector:
    matchLabels:
      app: theapp
      zone: dev
  template:
    metadata:
      labels:
        app: theapp
        zone: dev
        version: 1.0.1
    spec:
      containers:
      - name: theapp-pod
        image: smiron/theapp:20171111071026
        ports:
        - containerPort: 80