apiVersion: v1
kind: Service
metadata:
  name: theapp-svc
  labels:
    app: theapp
    zone: dev
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: theapp
    zone: dev